// LLD Quizzes — SOLID, patterns, and design problems

const QUIZZES_LLD = [
    {
        id: "lld-solid-patterns",
        title: "LLD: SOLID + Design Patterns",
        subtitle: "Principles and pattern selection",
        questionCount: 12,
        questions: [
            { q: "A class has methods: calculateSalary(), saveToDatabase(), generatePayslipPDF(), sendEmail(). Which SOLID principle is violated?", options: ["Open/Closed", "Single Responsibility — 4 unrelated reasons to change", "Liskov Substitution", "Dependency Inversion"], correct: 1, explanation: "SRP: salary logic, persistence, PDF formatting, and email are separate responsibilities. Changes to email templates shouldn't risk breaking salary calculation. Split into 4 focused classes." },
            { q: "interface Machine { print(); scan(); fax(); } — class BasicPrinter implements Machine but throws for scan() and fax(). Which principle is violated and what's the fix?", options: ["SRP — split the printer", "Interface Segregation — split into Printable, Scannable, Faxable interfaces", "Open/Closed — extend instead", "DIP — inject the scanner"], correct: 1, explanation: "ISP: BasicPrinter is forced to implement methods it can't support. Segregate: interface Printable { print(); }, interface Scannable { scan(); }. BasicPrinter implements only Printable. (This also fixes the LSP violation from the throwing methods.)" },
            { q: "You need to add PayPal support to a checkout that currently has: if(method==\"card\") {...} else if(method==\"upi\") {...}. The RIGHT fix follows which principle?", options: ["Add else if(method==\"paypal\")", "Open/Closed: PaymentMethod interface, each method a class, checkout depends on the interface — new methods added without editing checkout", "Singleton for PayPal", "Put PayPal logic in a util class"], correct: 1, explanation: "Open/Closed via Strategy: interface PaymentMethod { pay(amount); }. CardPayment, UPIPayment, PayPalPayment implement it. Checkout receives a PaymentMethod — closed for modification, open for extension." },
            { q: "Thread-safe Singleton: why must the instance field be declared 'volatile' in double-checked locking?", options: ["To make it faster", "Without volatile, another thread may see a partially-constructed instance due to instruction reordering", "Java requires it syntactically", "To prevent garbage collection"], correct: 1, explanation: "The JVM can reorder: (1) allocate memory, (2) assign reference, (3) run constructor. Another thread could see a non-null reference to a half-built object. volatile establishes a happens-before relationship preventing this." },
            { q: "Coffee shop: base coffee + any combination of milk, whip, caramel, extra shot. Which pattern avoids creating 16 subclasses?", options: ["Factory", "Builder", "Decorator — wrap the base with addon decorators, each adding cost and description", "Composite"], correct: 2, explanation: "Decorator: new CaramelDecorator(new MilkDecorator(new Espresso())). Each decorator implements Coffee and wraps another Coffee. N addons = N classes but 2^N combinations. Java's BufferedReader(new FileReader()) is this exact pattern." },
            { q: "Your Order class transitions: PLACED → PAID → SHIPPED → DELIVERED. cancel() is only valid before SHIPPED. Code is full of if(status == ...) checks. Which pattern?", options: ["Strategy", "State — each status is a class defining its valid transitions; invalid ones throw", "Observer", "Template Method"], correct: 1, explanation: "State pattern: PlacedState.cancel() works, ShippedState.cancel() throws. The Order delegates to its current state object. Adding a REFUNDED state = new class, no conditional editing." },
            { q: "Strategy and State patterns have identical UML structure. What distinguishes them?", options: ["Strategy uses interfaces, State uses abstract classes", "Intent: Strategy = client picks the algorithm; State = object transitions itself between states over its lifecycle", "State is thread-safe", "Strategy is only for algorithms with math"], correct: 1, explanation: "Structurally identical, semantically different. Strategy: externally chosen, usually fixed per use (checkout picks CardPayment). State: internally driven transitions (order moves itself from PAID to SHIPPED). Saying this distinction out loud is an interview power move." },
            { q: "You integrate a third-party SMS SDK whose interface doesn't match your NotificationChannel interface. You cannot modify the SDK. Which pattern?", options: ["Facade", "Adapter — a class implementing YOUR interface that internally calls the SDK", "Proxy", "Decorator"], correct: 1, explanation: "Adapter translates between incompatible interfaces: TwilioAdapter implements NotificationChannel, internally mapping send(notification) to Twilio's messages.create(...). Swap SMS providers by writing new adapters." },
            { q: "Ctrl+Z (undo) in a text editor is the classic use of which pattern?", options: ["Memento only", "Command — each operation is an object with execute() and undo(), stored in a history stack", "Observer", "Iterator"], correct: 1, explanation: "Command: CutCommand.execute() cuts and stores the text; undo() pastes it back. History stack of commands enables multi-level undo. (Memento is a valid alternative — snapshots vs reversible operations — but Command is the standard answer.)" },
            { q: "Approval workflow: expenses < $1K approved by Manager, < $10K by Director, < $100K by VP, else CEO. Which pattern?", options: ["State", "Chain of Responsibility — each approver handles or passes to the next", "Strategy", "Mediator"], correct: 1, explanation: "Chain of Responsibility: Manager → Director → VP → CEO. Each handler checks if it can approve; if not, forwards. Express/Spring middleware works identically. Adding a new tier = inserting a link, no existing code changes." },
            { q: "God class alert: your ParkingLot class finds spots, calculates fees, processes payments, sends receipts, and manages gates. First refactoring step?", options: ["Add more comments", "Extract responsibilities: SpotAssigner, FeeCalculator, PaymentProcessor, ReceiptService — ParkingLot orchestrates", "Make it a Singleton", "Convert to static methods"], correct: 1, explanation: "SRP refactoring: extract each responsibility into a focused class, inject them into ParkingLot (DIP), which becomes a thin orchestrator. Each piece is now independently testable and changeable." },
            { q: "Why is 'composition over inheritance' the default advice?", options: ["Inheritance is deprecated", "Composition allows runtime behavior swapping, avoids fragile base class problems, and doesn't force IS-A when you mean HAS-A", "Composition is faster at runtime", "Java doesn't support multiple inheritance"], correct: 1, explanation: "Deep inheritance couples subclasses to base implementation details (fragile base class). Composition + interfaces: swap behaviors at runtime (Strategy!), test with mocks, model HAS-A honestly. Inheritance is fine for true stable IS-A — which is rarer than it looks." }
        ]
    },
    {
        id: "lld-problems",
        title: "LLD: Design Problems",
        subtitle: "Parking, elevator, booking, games",
        questionCount: 12,
        questions: [
            { q: "Parking lot with 4 entry gates: two gates simultaneously find the same last free spot. What prevents double-assignment?", options: ["Only one gate operates at a time", "Atomic claim on the spot itself: occupant.compareAndSet(null, vehicle) — exactly one gate succeeds", "Global synchronized on the whole lot", "Random gate delays"], correct: 1, explanation: "CAS per spot: both gates may FIND the spot, but only one compareAndSet succeeds. The loser re-searches. Per-spot atomicity scales across gates; a global lock would serialize all parking. (Same concept as Redis SETNX in your HLD booking design!)" },
            { q: "Elevator going UP at floor 5 with internal stops {7, 9}. Why TreeSet instead of ArrayList for stops?", options: ["TreeSet uses less memory", "Sorted order gives O(log n) 'next stop in direction' via ceiling(); list would need sorting or scanning", "ArrayList is thread-unsafe", "TreeSet allows duplicates"], correct: 1, explanation: "SCAN algorithm needs 'nearest stop above current floor' — TreeSet.ceiling(6) → 7 in O(log n). Auto-sorted, no duplicates (pressing 7 twice = one stop). Data structure choice IS the design here." },
            { q: "Splitwise: why store money as long (cents/paise) instead of double?", options: ["long is faster", "Floating point can't represent 0.1 exactly — accumulating errors make balances drift; integers are exact", "double overflows", "JSON doesn't support double"], correct: 1, explanation: "0.1 + 0.2 != 0.3 in floating point. After thousands of splits, balances drift by paise — users notice! Store integer minor units (₹10.50 = 1050 paise), format only at display. Financial code rule #1." },
            { q: "Splitwise debt simplification: A owes B ₹500, B owes C ₹500, C owes A ₹200. Minimum transactions to settle?", options: ["3", "2 — net balances: A: -300, B: 0, C: +300 → A pays C ₹300... wait, that's 1!", "1 — net: A -300, B 0, C +300; single payment A→C ₹300 settles everything", "0"], correct: 2, explanation: "Net balances: A = -500+200 = -300, B = +500-500 = 0, C = +500-200 = +300. B is a pass-through! One transaction (A pays C ₹300) settles all. The greedy max-debtor/max-creditor matching finds this." },
            { q: "BookMyShow LLD: user's seat locks expire at 10:00, payment callback arrives 10:01, and another user now holds seat 2. Correct behavior?", options: ["Confirm anyway — payment succeeded", "Validate locks before confirming → fail → refund payment → notify user to rebook", "Steal seat 2 back", "Book remaining seats only"], correct: 1, explanation: "validate-before-confirm: the lock is gone, seat legitimately belongs to another user. Refund (compensating transaction — mini-Saga) and notify. Never force-book. This validate-confirm-compensate triple is the entire rubric for this question." },
            { q: "Chess: where does 'this move would leave my king in check' validation belong?", options: ["In each Piece.canMove()", "At Game level — simulate move, check king safety; it's a game rule spanning all pieces, not a piece movement rule", "In the King class", "In the UI"], correct: 1, explanation: "Piece.canMove() = 'is this movement shape legal for me?' Game = 'is this move legal in full context?' King-safety needs board-wide simulation — putting it in all 6 pieces duplicates logic and violates SRP." },
            { q: "Chess Queen implementation: Queen.canMove() returns rookLogic.canMove() || bishopLogic.canMove(). What does this demonstrate?", options: ["Inheritance abuse", "Composition of behaviors — Queen's movement IS the union of Rook and Bishop movement, reusing tested logic", "A Liskov violation", "Premature optimization"], correct: 1, explanation: "Elegant composition: queen = rook ∪ bishop movement. Reuses two tested implementations instead of duplicating ray-casting logic. Interviewers consistently reward this over a third copy of sliding-move code." },
            { q: "LRU Cache: why HashMap + doubly-linked list specifically? Why not HashMap + singly-linked list?", options: ["Singly-linked uses more memory", "Removing a node from the middle needs its PREV pointer — singly-linked would require O(n) traversal to find it", "HashMap requires doubly-linked", "No real difference"], correct: 1, explanation: "On get(), you unlink the accessed node from its current position — that needs node.prev. Doubly-linked = O(1) unlink. Singly-linked = O(n) scan to find the predecessor. This detail is exactly what the interviewer probes." },
            { q: "Token bucket (capacity 10, refill 1/sec) implemented with lazy refill. What background infrastructure does it need?", options: ["A timer thread adding tokens every second", "None — tokens are computed on demand: elapsed_time × rate, capped at capacity", "A cron job", "A Redis instance"], correct: 1, explanation: "Lazy refill: on each tryConsume(), compute tokens += (now - lastRefill) × rate, cap at capacity. No threads, no timers, exact same behavior. 'Do you need a background thread?' is the trap question — the answer is no." },
            { q: "Logger design: your async logger's BlockingQueue fills up because the file handler is slow. Best policy?", options: ["Block application threads until space frees", "Drop lowest-priority (DEBUG) entries first — losing debug logs beats blocking production requests", "Crash with OutOfMemoryError", "Unbounded queue"], correct: 1, explanation: "Backpressure policy: bounded queue + priority-aware dropping. Blocking app threads couples request latency to disk speed (the exact thing async logging prevents). Unbounded queues = eventual OOM. Say 'drop DEBUG first' — it shows production thinking." },
            { q: "Snake & Ladder: snakes and ladders are best modeled as...", options: ["Separate Snake and Ladder classes with different logic", "One Map<Integer,Integer> of jumps — a snake is a jump down, a ladder is a jump up; same abstraction", "A 2D grid", "Linked list of squares"], correct: 1, explanation: "Unification insight: both are 'land on A, move to B'. jumps.getOrDefault(pos, pos) handles everything. Separate classes work but miss the abstraction — spotting it is the differentiator on this 'easy' question." },
            { q: "Tic-Tac-Toe on n×n board: the row/col/diagonal counter trick (X=+1, O=-1) achieves what?", options: ["O(1) memory", "O(1) win detection per move instead of O(n) scanning — |rowSum[r]| == n means a win", "Prevents invalid moves", "Supports 3 players"], correct: 1, explanation: "Increment rowSum[r], colSum[c], diagonals on each move; any counter hitting ±n = win. O(1) per move. Keep the grid too — it validates 'is cell empty'. Counters index wins; grid validates moves. You need both." }
        ]
    }
];

QUIZZES.push(...QUIZZES_LLD);
